[google.flow]
# it depends on your environment
redirect_uri="http://localhost:8501/"

[google.client_secret.web]
client_id = "your_client_id"
project_id = "your_project_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "your_client_secret"

# it depends on your environment
redirect_uris = ["http://localhost:8501/"]
javascript_origins = ["http://localhost:8501""]


